#!/usr/bin/perl
use strict;
use warnings;
use CAH;
use Robit;
use POE;

my $spec = CAH->spec();
$spec->{channels} = ['##cah'];
$spec->{nick} = 'jdcah';

my $qq = Robit->new(%$spec);
$qq->spawn();
$poe_kernel->run();
